### ISSUE TITLE
Windows Samples fail with error thread exited with code 0 on Windows 10

### ISSUE THREAD

**Issue by CharlieD111** [opentok/opentok-windows-sdk-samples#19]
Tried the Windows BasicVideoChat and SimpleMultiparty samples using the same build of apps on 3 different Window 10 dev machines. On 2 systems the app will not steam video out and fails with a message similar to "The thread 0x42d0 has exited with code 0 (0x0)". No other info.

One build (OpenTok 2.16.1 VS2019  Debug on Win 10 Pro 10.0.17763 .on VMWareWorkstation 15) does work with no errors. All have the VS15 C++ redistributable. The other 2 builds are on native Win 10 machines, not VMs (eg Win 10 Pro 10.0.18362),. Cameras stream ok on all machines.

Help appreciated, thanks.

**Comment by CharlieD111** [comment]
UPDATE : It looks like something to do with the USB WebCam Capabilities. Swapping cameras around give different results with result that the PC that has a logitech 920 webcam with Microphone always streaming out to another client.

**Comment by MichaelJolley** [comment]
@CharlieD111 are you experiencing this with our newest Windows SDK? I've pulled the repo onto a clean install of Windows 10 and all seems to be working.

**Comment by CharlieD111** [comment]
Thanks for the follow up but sorry but our project was cancelled so no longer have the dev environment to test this.

**Comment by MichaelJolley** [comment]
No worries.  I'm going to close this for now and if you experience it in the future, feel free to re-open.
