### ISSUE TITLE
the feature that allows to share screen and camera in an WPF App

### ISSUE THREAD

**Issue by DavidSilwal** [opentok/opentok-windows-sdk-samples#31]
I am trying to implement the feature that allows to share screen and camera in an WPF App.
I have researched OpenTok examples and samples and figured they show only one feature per program sample.
**Question**: 
Should code supply two Publishers (one equipped with Camera and one with Screensharing capturer) 
and switch them, for example
or better stick with single Publisher and flip between the BaseVideoCapturer and ScreensharingCapturer as I need? But I need to implement the screen share as needed during the conference talk.

It would really be thankful if folks provide some sample or document to get the work done.

**Comment by MichaelJolley** [comment]
Hi @DavidSilwal, you would want separate publishers for the speaker and screenshare. Then modify your layout as needed to display the correct stream.
