### ISSUE TITLE
AudioBus output wave format and bits per sample

### ISSUE THREAD

**Issue by hendrihendri** [opentok/opentok-windows-sdk-samples#35]
Hi, I am trying to implement custom audio renderer/capturer using `IAudioDevice` and `SetCustomAudioDevice` API. I noticed that the interface were only asked to provide `SamplingRate` and `Channels` as the renderer/capturer settings via `GetAudioCapturerSettings`/`GetAudioRendererSettings`. What is the expected wave format and bits per sample that the `AudioBus` is expecting (e.g. PCM, IEEE)?

Thanks!

**Comment by sergioturgil-vonage** [comment]
Hi! It expects PCM with 2 byte signed integers.

The batches of samples provided via the write_samples and read_samples callbacks have the following example format:

F1C1 F1C2 F2C1 F2C2 ... FNC1 FNC2

Each of these FXCY is a signed 2-byte short with the value for frame X and channel Y (this is of course for a stereo sequence with two channels. A mono sequence would only include the values for C1).

Please, let me know if I wasn't too clear on the explanation.

**Comment by v-kpheng** [comment]
Thanks, @sergioturgil-vonage!  @hendrihendri, any other issues, please let us know.  Thanks!
