### ISSUE TITLE
Can't I use OpenTok.Client on Net Core 5.0?

### ISSUE THREAD

**Issue by SID9-HoneyBee** [opentok/opentok-windows-sdk-samples#39]
A WPF project was created in DotNet Core 5 and OpenTok.Client was added using Nuget Package.

However, it cannot be referenced normally in the source code of my project.

**Comment by v-kpheng** [comment]
Closing, since a lot new updates were added since this question was posted.

Can you please try again using our most recent version?  Thanks!
