### ISSUE TITLE
HRESULT: [0x887A0001], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall]

### ISSUE THREAD

**Issue by Borman95** [opentok/opentok-windows-sdk-samples#40]
HRESULT: [0x887A0001], Module: [SharpDX.DXGI], ApiCode: [DXGI_ERROR_INVALID_CALL/InvalidCall]

**Comment by v-kpheng** [comment]
@Borman95, thanks for filing this issue.

That said, there's not enough information to root cause.  I'm going to close, given lack of information.  Also, I've updated the Bug Report template to ask more specific questions.  Thanks!
