### ISSUE TITLE
OpenTok UWP Applications

### ISSUE THREAD

**Issue by ycagri** [opentok/opentok-windows-sdk-samples#42]
Is it possible to use OpenTok in UWP applications? [Here](https://tokbox.com/developer/sdks/windows/), it is stated that OpenTok supports UWP desktop apps with version 2.23.0. I am able to add NuGet package. However, I can't see `OpenTok` namespace.

**Comment by breenbob** [comment]
I too am wondering this. There are regular new releases of Windows SDK and UWP support released 2 months ago, but samples haven't been touched in 2 years, GitHub issues not replied to in over a year, and no samples of it working in a UWP app whatsoever, here or anywhere else on the web. What's going on?

**Comment by ycagri** [comment]
I have solved the issue via support. The minimum target version of the UWP app should be 19041, then you will be able to use the library. However, this repo seems dead as you said @breenbob

**Comment by v-kpheng** [comment]
Repo isn't dead :-)

We're working on adding/updating sample apps but it'll take some time.

Closing, since it looks like @ycagri got the answer sought.
