### ISSUE TITLE
App crash

### ISSUE THREAD

**Issue by wesoos** [opentok/opentok-windows-sdk-samples#52]
Every now and then my app crashes while using OpenTok.  It's not consistent and I can't pin point where it happens.  Below are the logs that I can pull:

Event Viewer:

CoreCLR Version: 7.0.523.17405
.NET Version: 7.0.5
Description: The process was terminated due to an unhandled exception.
Exception Info: exception code c0000005, exception address 00007FF92BEE8BA4
Stack:

Faulting module name: opentok.DLL, version: 2.25.0.0, time stamp: 0x642b5e27
Exception code: 0xc0000005
Fault offset: 0x0000000000f38ba4
Faulting process id: 0x13f8
Faulting application start time: 0x01d977a9194f2373

I know it's not much to go on, but any ideas?

Thanks

**Comment by sergioturgil-vonage** [comment]
Thx for the feedback!
We're aware of some crashes that have been happening lately with that access violation code.
We think that there might be some heap corruption involved and are working on it. I hope we can fix it very soon.

**Comment by wesoos** [comment]
Ok thank you

**Comment by vladhelmes** [comment]
Hello, 
We are also experiencing this crash (and it took us 4 days to narrow it down). Any idea when a fix will be released?
Thanks
Vlad

**Comment by wesoos** [comment]
Hello, any update on when this will be released?  It is causing major issues with us...

**Comment by sergioturgil-vonage** [comment]
It has already been merged so it will make it to 2.25.1

**Comment by wesoos** [comment]
Hello, any ETA on release?

**Comment by wesoos** [comment]
@sergioturgil-vonage Hi, when will you be releasing this fix?

**Comment by sergioturgil-vonage** [comment]
Not in charge of releases but code freeze for 2.25.1 is already on so it should be coming out in the next days.

**Comment by sergioturgil-vonage** [comment]
> @sergioturgil-vonage, can you please share the jira ticket that this was fixed in? Thanks!

https://jira.vonage.com/browse/VIDCS-813

**Comment by v-kpheng** [comment]
Closing, since this was fixed in Windows SDK 2.25.1.

**Comment by wesoos** [comment]
Hi Sergio,

I've created another ticket for this issue...
