### ISSUE TITLE
Write a CustomVideoCapturer

### ISSUE THREAD

**Issue by Selonka** [opentok/opentok-windows-sdk-samples#81]
Hi,

I like to get a videostream from a local RTSP-Source and want to publish it to a session. I looked for examples in this repro and only found the ScreenSharingCapturer which ist implements the IVideoCapturer interface.  As far as I understand I have to break down my rtsp-stream into single frames and hand them over to the frameconsumer is that right ?

Thank you in advance!

Greetings Selonka

**Comment by sergioturgil-vonage** [comment]
Apologies for the belated reply.

Yes, you got that right.
Just implement IVideoCapturer, get frames one by one from your source and hand them over to the FrameConsumer. There's really no requirement for the frame rate at which you provide the frames, but it should be as close as possible to what you report in the GetCaptureSettings.
Also, this GetCaptureSettings method is called by the SDK between Init and Start, so make sure to have the correct capture settings by that time.

**Comment by Selonka** [comment]
Hi, thanks for the explanation.
